In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [6]:
a = np.array([[1,2,3],[154,54,45]])
print(a)
print(a.shape)

[[  1   2   3]
 [154  54  45]]
(2, 3)


In [9]:
l1 = [2,3,4,5]
l2 = [12,13,14,15]
list(map(lambda x,y : x*y,l1,l2))

[24, 39, 56, 75]

In [13]:
a1 = np.array(l1)
a2 = np.array(l2)
a3 = a1*a2
print(a3)
print(type(a3))
print(a1+a2)
print(a1**2)

[24 39 56 75]
<class 'numpy.ndarray'>
[14 16 18 20]
[ 4  9 16 25]


In [14]:
help(np.ones)

Help on function ones in module numpy.core.numeric:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    zeros, ones_like
    
    Examples
    --------
    >>> np.ones(5)
    array([ 1.,  1.,  1.,  1.,  1.])
    
    >>> np.ones((5,), dtype=int)
    array([1, 1, 1, 1, 1])
    
    >>> np.ones((2, 1))
    array([[ 1.],
           [ 1.]])
    
    >>> s = (2,2)
    >>> np.ones(s)
    ar

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.ones([2,3],dtype=np.int)

array([[1, 1, 1],
       [1, 1, 1]])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros([1,4],dtype=np.int)

array([[0, 0, 0, 0]])

In [20]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.random.random((3,4))

array([[0.4284634 , 0.34136783, 0.72869904, 0.92797423],
       [0.62499375, 0.10966274, 0.75378496, 0.52846449],
       [0.54482453, 0.7392791 , 0.64755276, 0.39681756]])

In [25]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [26]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [28]:
np.arange(1,20,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [29]:
arr = np.random.random((1000,300))

In [33]:
print(arr[1,1:10])

[0.56262039 0.18291353 0.56047094 0.94817584 0.89139575 0.27560856
 0.92213033 0.6312151  0.82362626]


In [34]:
arr.shape

(1000, 300)

In [35]:
arr.dtype

dtype('float64')

In [36]:
type(arr)

numpy.ndarray

In [38]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [39]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a[2:7]

array([2, 3, 4, 5, 6])

In [41]:
a[1:10:2]

array([1, 3, 5, 7, 9])

In [42]:
a[[2,5,6]]

array([2, 5, 6])

In [44]:
a[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a = np.array([[1,2,3],[2,3,45],[4,5,6]])
a

array([[ 1,  2,  3],
       [ 2,  3, 45],
       [ 4,  5,  6]])

In [48]:
a[2,1]

5

In [49]:
a[:2]

array([[ 1,  2,  3],
       [ 2,  3, 45]])

In [50]:
a[:2,:3]

array([[ 1,  2,  3],
       [ 2,  3, 45]])

In [52]:
a[0,:2]

array([1, 2])

In [54]:
a = np.arange(6)

In [56]:
a

array([0, 1, 2, 3, 4, 5])

In [57]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [65]:
a = a.reshape(2,-1)

In [66]:
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [69]:
b = np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [70]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [72]:
np.vstack((a,b))

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [73]:
np.hstack((b,a))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [74]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [75]:
np.log(a)

C:\Users\narla\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791]])

In [76]:
np.exp(a)

array([[  1.        ,   2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003, 148.4131591 ]])

In [77]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427]])

In [78]:
np.tan(a)

array([[ 0.        ,  1.55740772, -2.18503986],
       [-0.14254654,  1.15782128, -3.38051501]])

In [80]:
a = np.arange(1,20)

In [81]:
f = np.vectorize(lambda x:x/x+1)
f(a)

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2.])

In [84]:
a = np.arange(6).reshape(3,-1)
a


array([[0, 1],
       [2, 3],
       [4, 5]])

In [85]:
b = np.arange(6).reshape(3,-1)
b


array([[0, 1],
       [2, 3],
       [4, 5]])

In [86]:
np.multiply(a,b)

array([[ 0,  1],
       [ 4,  9],
       [16, 25]])

In [88]:
np.dot(a,b.T)

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])

In [90]:
import numpy as np
import pandas as pd

In [93]:
a = pd.Series([2,3,43,3,5,6])
print(a)

0     2
1     3
2    43
3     3
4     5
5     6
dtype: int64


In [96]:
a = pd.Series([1,2,3,4],index=['a','b','c','d'])
a

a    1
b    2
c    3
d    4
dtype: int64

In [99]:
dt = pd.date_range(start="11-03-2016",end="23-03-2016")
print(dt)

DatetimeIndex([], dtype='datetime64[ns]', freq='D')


In [100]:
a = pd.Series(np.arange(1,10))
a

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int32

In [102]:
a[1:4]

1    2
2    3
3    4
dtype: int32

In [104]:
a.apply(lambda x:x**2)

0     1
1     4
2     9
3    16
4    25
5    36
6    49
7    64
8    81
dtype: int64

In [105]:
np.arange(1,10).apply(lambda x:x**2)

AttributeError: 'numpy.ndarray' object has no attribute 'apply'

In [108]:
df = pd.DataFrame({
    'name':['a','b','c','d'],
    'age':[23,3,54,65]
})
df

name  age
0    a   23
1    b    3
2    c   54
3    d   65

In [110]:
df = pd.read_csv("D:/PGDDS/Python_Classes/Datasets/employees.csv")
df.head()

First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
0    Douglas    Male   8/6/1993        12:42 PM   97308    6.945   
1     Thomas    Male  3/31/1996         6:53 AM   61933    4.170   
2      Maria  Female  4/23/1993        11:17 AM  130590   11.858   
3      Jerry    Male   3/4/2005         1:00 PM  138705    9.340   
4      Larry    Male  1/24/1998         4:47 PM  101004    1.389   

  Senior Management             Team  
0              True        Marketing  
1              True              NaN  
2             False          Finance  
3              True          Finance  
4              True  Client Services

In [114]:
df.tail()

First Name Gender  Start Date Last Login Time  Salary  Bonus %  \
995      Henry    NaN  11/23/2014         6:09 AM  132483   16.655   
996    Phillip   Male   1/31/1984         6:30 AM   42392   19.675   
997    Russell   Male   5/20/2013        12:39 PM   96914    1.421   
998      Larry   Male   4/20/2013         4:45 PM   60500   11.985   
999     Albert   Male   5/15/2012         6:24 PM  129949   10.169   

    Senior Management                  Team  
995             False          Distribution  
996             False               Finance  
997             False               Product  
998             False  Business Development  
999              True                 Sales

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
First Name           933 non-null object
Gender               855 non-null object
Start Date           1000 non-null object
Last Login Time      1000 non-null object
Salary               1000 non-null int64
Bonus %              1000 non-null float64
Senior Management    933 non-null object
Team                 957 non-null object
dtypes: float64(1), int64(1), object(6)
memory usage: 62.6+ KB


In [116]:
df.describe()

Salary      Bonus %
count    1000.000000  1000.000000
mean    90662.181000    10.207555
std     32923.693342     5.528481
min     35013.000000     1.015000
25%     62613.000000     5.401750
50%     90428.000000     9.838500
75%    118740.250000    14.838000
max    149908.000000    19.944000

In [119]:
df.columns

Index(['First Name', 'Gender', 'Start Date', 'Last Login Time', 'Salary',
       'Bonus %', 'Senior Management', 'Team'],
      dtype='object')

In [120]:
df.values

array([['Douglas', 'Male', '8/6/1993', ..., 6.945, True, 'Marketing'],
       ['Thomas', 'Male', '3/31/1996', ..., 4.17, True, nan],
       ['Maria', 'Female', '4/23/1993', ..., 11.857999999999999, False,
        'Finance'],
       ...,
       ['Russell', 'Male', '5/20/2013', ..., 1.421, False, 'Product'],
       ['Larry', 'Male', '4/20/2013', ..., 11.985, False,
        'Business Development'],
       ['Albert', 'Male', '5/15/2012', ..., 10.169, True, 'Sales']],
      dtype=object)

In [122]:
df.head()

First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
0    Douglas    Male   8/6/1993        12:42 PM   97308    6.945   
1     Thomas    Male  3/31/1996         6:53 AM   61933    4.170   
2      Maria  Female  4/23/1993        11:17 AM  130590   11.858   
3      Jerry    Male   3/4/2005         1:00 PM  138705    9.340   
4      Larry    Male  1/24/1998         4:47 PM  101004    1.389   

  Senior Management             Team  
0              True        Marketing  
1              True              NaN  
2             False          Finance  
3              True          Finance  
4              True  Client Services

In [123]:
df1 = df 

In [124]:
df.sort_values(by='Gender').head()

First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
500  Christine  Female   2/1/2003         1:11 PM   72613   11.126   
430     Andrea  Female  10/1/2010        11:54 AM   79123   19.422   
429       Rose  Female  5/28/2015         8:40 AM  149903    5.630   
793     Andrea  Female  7/22/1999         9:25 AM  149105   13.707   
794     Nicole  Female   3/1/2004         5:17 PM   44021   10.286   

    Senior Management             Team  
500             False            Legal  
430             False     Distribution  
429             False  Human Resources  
793              True     Distribution  
794             False              NaN

In [127]:
df.sort_values(by=['Salary','Gender']).head()

First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
576    Michael    Male  7/30/1993         5:35 PM   35013   14.879   
238      Kevin    Male  3/25/1982         7:31 AM   35061    5.128   
82      Steven    Male  3/30/1980         9:20 PM   35095    8.379   
63     Matthew    Male   1/2/2013        10:33 PM   35203   18.040   
650    Cynthia  Female   7/5/1986         1:24 AM   35381   11.749   

    Senior Management             Team  
576             False          Product  
238             False            Legal  
82               True  Client Services  
63              False  Human Resources  
650             False          Finance

In [128]:
df1 = df[['First Name','Gender']]

In [129]:
df1.head()

First Name  Gender
0    Douglas    Male
1     Thomas    Male
2      Maria  Female
3      Jerry    Male
4      Larry    Male

In [130]:
df[2:4]

First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
2      Maria  Female  4/23/1993        11:17 AM  130590   11.858   
3      Jerry    Male   3/4/2005         1:00 PM  138705    9.340   

  Senior Management     Team  
2             False  Finance  
3              True  Finance

In [131]:
df[:100:25]

First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
0     Douglas    Male   8/6/1993        12:42 PM   97308    6.945   
25        NaN    Male  10/8/2012         1:12 AM   37076   18.576   
50      Nancy  Female  9/23/2000         8:05 AM   94976   13.830   
75     Bonnie  Female   7/2/1991         1:27 AM  104897    5.118   

   Senior Management             Team  
0               True        Marketing  
25               NaN  Client Services  
50              True      Engineering  
75              True  Human Resources

In [132]:
df.columns

Index(['First Name', 'Gender', 'Start Date', 'Last Login Time', 'Salary',
       'Bonus %', 'Senior Management', 'Team'],
      dtype='object')

In [133]:
df['Salary'].head()

0     97308
1     61933
2    130590
3    138705
4    101004
Name: Salary, dtype: int64

In [134]:
df[['First Name','Salary']].head()

First Name  Salary
0    Douglas   97308
1     Thomas   61933
2      Maria  130590
3      Jerry  138705
4      Larry  101004

In [136]:
df[:2]

First Name Gender Start Date Last Login Time  Salary  Bonus %  \
0    Douglas   Male   8/6/1993        12:42 PM   97308    6.945   
1     Thomas   Male  3/31/1996         6:53 AM   61933    4.170   

  Senior Management       Team  
0              True  Marketing  
1              True        NaN

In [138]:
df.head()

First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
0    Douglas    Male   8/6/1993        12:42 PM   97308    6.945   
1     Thomas    Male  3/31/1996         6:53 AM   61933    4.170   
2      Maria  Female  4/23/1993        11:17 AM  130590   11.858   
3      Jerry    Male   3/4/2005         1:00 PM  138705    9.340   
4      Larry    Male  1/24/1998         4:47 PM  101004    1.389   

  Senior Management             Team  
0              True        Marketing  
1              True              NaN  
2             False          Finance  
3              True          Finance  
4              True  Client Services

In [139]:
help(df.iloc)

Help on _iLocIndexer in module pandas.core.indexing object:

class _iLocIndexer(_LocationIndexer)
 |  Purely integer-location based indexing for selection by position.
 |  
 |  ``.iloc[]`` is primarily integer position based (from ``0`` to
 |  ``length-1`` of the axis), but may also be used with a boolean
 |  array.
 |  
 |  Allowed inputs are:
 |  
 |  - An integer, e.g. ``5``.
 |  - A list or array of integers, e.g. ``[4, 3, 0]``.
 |  - A slice object with ints, e.g. ``1:7``.
 |  - A boolean array.
 |  - A ``callable`` function with one argument (the calling Series, DataFrame
 |    or Panel) and that returns valid output for indexing (one of the above)
 |  
 |  ``.iloc`` will raise ``IndexError`` if a requested indexer is
 |  out-of-bounds, except *slice* indexers which allow out-of-bounds
 |  indexing (this conforms with python/numpy *slice* semantics).
 |  
 |  See more at :ref:`Selection by Position <indexing.integer>`
 |  
 |  Method resolution order:
 |      _iLocIndexer
 |     

In [140]:
df.iloc[2,4]

130590

In [141]:
df.head()

First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
0    Douglas    Male   8/6/1993        12:42 PM   97308    6.945   
1     Thomas    Male  3/31/1996         6:53 AM   61933    4.170   
2      Maria  Female  4/23/1993        11:17 AM  130590   11.858   
3      Jerry    Male   3/4/2005         1:00 PM  138705    9.340   
4      Larry    Male  1/24/1998         4:47 PM  101004    1.389   

  Senior Management             Team  
0              True        Marketing  
1              True              NaN  
2             False          Finance  
3              True          Finance  
4              True  Client Services

In [142]:
df.iloc[5]

First Name              Dennis
Gender                    Male
Start Date           4/18/1987
Last Login Time        1:35 AM
Salary                  115163
Bonus %                 10.125
Senior Management        False
Team                     Legal
Name: 5, dtype: object

In [146]:
df.iloc[5:7,:]

First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
5     Dennis    Male  4/18/1987         1:35 AM  115163   10.125   
6       Ruby  Female  8/17/1987         4:20 PM   65476   10.012   

  Senior Management     Team  
5             False    Legal  
6              True  Product

In [151]:
df.iloc[2:6,[0,1,2]]

First Name  Gender Start Date
2      Maria  Female  4/23/1993
3      Jerry    Male   3/4/2005
4      Larry    Male  1/24/1998
5     Dennis    Male  4/18/1987

In [153]:
df.iloc[:3,2]

0     8/6/1993
1    3/31/1996
2    4/23/1993
Name: Start Date, dtype: object

In [157]:
df.loc[1:12,['Gender','First Name']]

Gender First Name
1     Male     Thomas
2   Female      Maria
3     Male      Jerry
4     Male      Larry
5     Male     Dennis
6   Female       Ruby
7   Female        NaN
8   Female     Angela
9   Female    Frances
10  Female     Louise
11  Female      Julie
12    Male    Brandon

In [158]:
df.iloc[1:10,2:4]

Start Date Last Login Time
1   3/31/1996         6:53 AM
2   4/23/1993        11:17 AM
3    3/4/2005         1:00 PM
4   1/24/1998         4:47 PM
5   4/18/1987         1:35 AM
6   8/17/1987         4:20 PM
7   7/20/2015        10:43 AM
8  11/22/2005         6:29 AM
9    8/8/2002         6:51 AM

In [160]:
df.loc[1:10,['Start Date']]

Start Date
1    3/31/1996
2    4/23/1993
3     3/4/2005
4    1/24/1998
5    4/18/1987
6    8/17/1987
7    7/20/2015
8   11/22/2005
9     8/8/2002
10   8/12/1980

In [162]:
df.head()

First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
0    Douglas    Male   8/6/1993        12:42 PM   97308    6.945   
1     Thomas    Male  3/31/1996         6:53 AM   61933    4.170   
2      Maria  Female  4/23/1993        11:17 AM  130590   11.858   
3      Jerry    Male   3/4/2005         1:00 PM  138705    9.340   
4      Larry    Male  1/24/1998         4:47 PM  101004    1.389   

  Senior Management             Team  
0              True        Marketing  
1              True              NaN  
2             False          Finance  
3              True          Finance  
4              True  Client Services

In [163]:
df.columns

Index(['First Name', 'Gender', 'Start Date', 'Last Login Time', 'Salary',
       'Bonus %', 'Senior Management', 'Team'],
      dtype='object')

In [165]:
df.describe()

Salary      Bonus %
count    1000.000000  1000.000000
mean    90662.181000    10.207555
std     32923.693342     5.528481
min     35013.000000     1.015000
25%     62613.000000     5.401750
50%     90428.000000     9.838500
75%    118740.250000    14.838000
max    149908.000000    19.944000

In [172]:
df.loc[df.Salary>1000,]

First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
0      Douglas    Male    8/6/1993        12:42 PM   97308    6.945   
1       Thomas    Male   3/31/1996         6:53 AM   61933    4.170   
2        Maria  Female   4/23/1993        11:17 AM  130590   11.858   
3        Jerry    Male    3/4/2005         1:00 PM  138705    9.340   
4        Larry    Male   1/24/1998         4:47 PM  101004    1.389   
5       Dennis    Male   4/18/1987         1:35 AM  115163   10.125   
6         Ruby  Female   8/17/1987         4:20 PM   65476   10.012   
7          NaN  Female   7/20/2015        10:43 AM   45906   11.598   
8       Angela  Female  11/22/2005         6:29 AM   95570   18.523   
9      Frances  Female    8/8/2002         6:51 AM  139852    7.524   
10      Louise  Female   8/12/1980         9:01 AM   63241   15.132   
11       Julie  Female  10/26/1997         3:19 PM  102508   12.637   
12     Brandon    Male   12/1/1980         1:08 AM  112807   17.492   
13        Gary    Male   1/27/2008        11:40 PM  109831    5.831   
14    Kimberly  Female   1/14/1999         7:13 AM   41426   14.543   
15     Lillian  Female    6/5/2016         6:09 AM   59414    1.256   
16      Jeremy    Male   9/21/2010         5:56 AM   90370    7.369   
17       Shawn    Male   12/7/1986         7:45 PM  111737    6.414   
18       Diana  Female  10/23/1981        10:27 AM  132940   19.082   
19       Donna  Female   7/22/2010         3:48 AM   81014    1.894   
20        Lois     NaN   4/22/1995         7:18 PM   64714    4.934   
21     Matthew    Male    9/5/1995         2:12 AM  100612   13.645   
22      Joshua     NaN    3/8/2012         1:58 AM   90816   18.816   
23         NaN    Male   6/14/2012         4:19 PM  125792    5.042   
24        John    Male    7/1/1992        10:08 PM   97950   13.873   
25         NaN    Male   10/8/2012         1:12 AM   37076   18.576   
26       Craig    Male   2/27/2000         7:45 AM   37598    7.757   
27       Scott     NaN   7/11/1991         6:58 PM  122367    5.218   
28       Terry    Male  11/27/1981         6:30 PM  124008   13.464   
29    Benjamin    Male   1/26/2005        10:06 PM   79529    7.008   
..         ...     ...         ...             ...     ...      ...   
970      Alice  Female    9/3/1988         8:54 PM   63571   15.397   
971    Patrick    Male  12/30/2002         2:01 AM   75423    5.368   
972     Victor     NaN   7/28/2006         2:49 PM   76381   11.159   
973    Russell    Male   5/10/2013        11:08 PM  137359   11.105   
974      Harry    Male   8/30/2011         6:31 PM   67656   16.455   
975      Susan  Female    4/7/1995        10:05 PM   92436   12.467   
976     Denise  Female  10/19/1992         5:42 AM  137954    4.195   
977      Sarah  Female   12/4/1995         9:16 AM  124566    5.949   
978       Sean    Male   1/17/1983         2:23 PM   66146   11.178   
979     Ernest    Male   7/20/2013         6:41 AM  142935   13.198   
980   Kimberly  Female   1/26/2013        12:57 AM   46233    8.862   
981      James    Male   1/15/1993         5:19 PM  148985   19.280   
982       Rose  Female    4/6/1982        10:43 AM   91411    8.639   
983       John    Male  12/23/1982        10:35 PM  146907   11.738   
984      Maria  Female  10/15/2011         4:53 PM   43455   13.040   
985    Stephen     NaN   7/10/1983         8:10 PM   85668    1.909   
986      Donna  Female  11/26/1982         7:04 AM   82871   17.999   
987     Gloria  Female   12/8/2014         5:08 AM  136709   10.331   
988      Alice  Female   10/5/2004         9:34 AM   47638   11.209   
989     Justin     NaN   2/10/1991         4:58 PM   38344    3.794   
990      Robin  Female   7/24/1987         1:35 PM  100765   10.982   
991       Rose  Female   8/25/2002         5:12 AM  134505   11.051   
992    Anthony    Male  10/16/2011         8:35 AM  112769   11.625   
993       Tina  Female   5/15/1997         3:53 PM   56450   19.040   
994     George    Male   6/2

In [175]:
df.loc[(df.Salary > 1000) &(df.Gender=='Female')]

First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
2        Maria  Female   4/23/1993        11:17 AM  130590   11.858   
6         Ruby  Female   8/17/1987         4:20 PM   65476   10.012   
7          NaN  Female   7/20/2015        10:43 AM   45906   11.598   
8       Angela  Female  11/22/2005         6:29 AM   95570   18.523   
9      Frances  Female    8/8/2002         6:51 AM  139852    7.524   
10      Louise  Female   8/12/1980         9:01 AM   63241   15.132   
11       Julie  Female  10/26/1997         3:19 PM  102508   12.637   
14    Kimberly  Female   1/14/1999         7:13 AM   41426   14.543   
15     Lillian  Female    6/5/2016         6:09 AM   59414    1.256   
18       Diana  Female  10/23/1981        10:27 AM  132940   19.082   
19       Donna  Female   7/22/2010         3:48 AM   81014    1.894   
30   Christina  Female    8/6/2002         1:19 PM  118780    9.096   
33        Jean  Female  12/18/1993         9:07 AM  119082   16.180   
35     Theresa  Female  10/10/2006         1:12 AM   85182   16.675   
36      Rachel  Female   2/16/2009         8:47 PM  142032   12.599   
37       Linda  Female  10/19/1981         8:49 PM   57427    9.557   
38   Stephanie  Female   9/13/1986         1:52 AM   36844    5.574   
42     Beverly  Female    9/9/1998         8:26 PM  121918   15.835   
43     Marilyn  Female   12/7/1980         3:16 AM   73524    5.207   
44     Cynthia  Female  11/16/1988         6:54 PM  145146    7.482   
47       Kathy  Female   6/22/2005         4:51 AM   66820    9.000   
50       Nancy  Female   9/23/2000         8:05 AM   94976   13.830   
54        Sara  Female   8/15/2007         9:23 AM   83677    8.999   
55       Karen  Female  11/30/1999         7:46 AM  102488   17.653   
58     Theresa  Female   4/11/2010         7:18 AM   72670    1.481   
59       Irene  Female    5/7/1997         9:32 AM   66851   11.279   
61      Denise  Female   11/6/2001        12:03 PM  106862    3.699   
62         NaN  Female   6/12/2007         5:25 PM   58112   19.414   
66       Nancy  Female  12/15/2012        11:57 PM  125250    2.672   
67      Rachel  Female   8/16/1999         6:53 AM   51178    9.735   
..         ...     ...         ...             ...     ...      ...   
932     Bonnie  Female  12/23/2008         9:26 AM   90427    2.010   
933      Doris  Female    7/5/1993         5:54 PM  141439    3.799   
935      Alice  Female   3/23/1996         3:09 AM  131952   12.090   
936      Maria  Female   3/14/2003         5:23 PM   96250   10.056   
942       Lori  Female  11/20/2015         1:15 PM   75498    6.537   
946        NaN  Female   9/15/1985         1:50 AM  133472   16.941   
948     Ashley  Female   3/31/2006         1:24 PM  142410   11.048   
950      Paula  Female   5/21/1983        11:42 AM   58423   10.833   
951        NaN  Female   9/14/2010         5:19 AM  143638    9.662   
952     Teresa  Female   1/22/2013         3:17 PM  113425   11.907   
955      Sarah  Female   8/17/2014        11:08 PM  127118   11.176   
956    Beverly  Female  10/17/1986        12:51 AM   80838    8.115   
958     Gloria  Female  10/24/1987         4:43 AM   39833    9.631   
963        Ann  Female   9/23/1994        11:15 AM   89443   17.940   
965  Catherine  Female   9/25/1989         1:31 AM   68164   18.393   
968     Louise  Female   3/27/1995        10:27 PM   43050   11.671   
969      Linda  Female    2/4/2010         8:49 PM   44486   17.308   
970      Alice  Female    9/3/1988         8:54 PM   63571   15.397   
975      Susan  Female    4/7/1995        10:05 PM   92436   12.467   
976     Denise  Female  10/19/1992         5:42 AM  137954    4.195   
977      Sarah  Female   12/4/1995         9:16 AM  124566    5.949   
980   Kimberly  Female   1/26/2013        12:57 AM   46233    8.862   
982       Rose  Female    4/6/1982        10:43 AM   91411    8.639   
984      Maria  Female  10/15/2011         4:53 PM   43455   13.040   
986      Donna  Female  11/2

In [177]:
cust = pd.read_csv("D:/PGDDS/Python/global_sales_data/cust_dimen.csv")
marketing = pd.read_csv("D:/PGDDS/Python/global_sales_data/market_fact.csv")
orders = pd.read_csv("D:/PGDDS/Python/global_sales_data/orders_dimen.csv")
prod = pd.read_csv("D:/PGDDS/Python/global_sales_data/prod_dimen.csv")
shipping = pd.read_csv("D:/PGDDS/Python/global_sales_data/shipping_dimen.csv")


In [180]:
marketing.head()
cust.head()

Customer_Name Province   Region Customer_Segment Cust_id
0  MUHAMMED MACINTYRE  NUNAVUT  NUNAVUT   SMALL BUSINESS  Cust_1
1        BARRY FRENCH  NUNAVUT  NUNAVUT         CONSUMER  Cust_2
2       CLAY ROZENDAL  NUNAVUT  NUNAVUT        CORPORATE  Cust_3
3      CARLOS SOLTERO  NUNAVUT  NUNAVUT         CONSUMER  Cust_4
4        CARL JACKSON  NUNAVUT  NUNAVUT        CORPORATE  Cust_5

In [183]:
df1 = pd.merge(marketing,cust,how="inner",on="Cust_id")
df1.head()

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
0  Ord_5446  Prod_16  SHP_7609  Cust_1818   136.81      0.01              23   
1  Ord_5406  Prod_13  SHP_7549  Cust_1818    42.27      0.01              13   
2  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00              26   
3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.89      0.09              43   
4  Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.15      0.08              35   

    Profit  Shipping_Cost  Product_Base_Margin  Customer_Name Province Region  \
0   -30.51           3.60                 0.56  AARON BERGMAN  ALBERTA   WEST   
1     4.56           0.93                 0.54  AARON BERGMAN  ALBERTA   WEST   
2  1148.90           2.50                 0.59  AARON BERGMAN  ALBERTA   WEST   
3   729.34          14.30                 0.37  AARON BERGMAN  ALBERTA   WEST   
4  1219.87          26.30                 0.38  AARON BERGMAN  ALBERTA   WEST   

  Customer_Segment  
0        CORPORATE  
1        CORPORATE  
2        CORPORATE  
3        CORPORATE  
4        CORPORATE

In [189]:
df1.loc[df1['Customer_Segment'] == 'CORPORATE']

Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
0     Ord_5446  Prod_16  SHP_7609  Cust_1818   136.8100      0.01   
1     Ord_5406  Prod_13  SHP_7549  Cust_1818    42.2700      0.01   
2     Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.6900      0.00   
3     Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.8900      0.09   
4     Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.1500      0.08   
5     Ord_5446   Prod_6  SHP_7608  Cust_1818   164.0200      0.03   
6       Ord_31  Prod_12    SHP_41    Cust_26    14.7600      0.01   
45    Ord_4768  Prod_12  SHP_6650  Cust_1579     3.8500      0.08   
46    Ord_4690   Prod_2  SHP_6545  Cust_1579   904.1200      0.07   
47    Ord_4659   Prod_6  SHP_6493  Cust_1579  1451.5900      0.06   
48    Ord_4622  Prod_12  SHP_6437  Cust_1579    56.2600      0.00   
49    Ord_4657   Prod_5  SHP_6490  Cust_1579   336.8600      0.06   
50    Ord_4682   Prod_5  SHP_6531  Cust_1579    63.9100      0.04   
51    Ord_4768   Prod_4  SHP_6651  Cust_1579   547.0005      0.08   
52    Ord_4755  Prod_13  SHP_6628  Cust_1579     3.4100      0.06   
53    Ord_4659   Prod_6  SHP_6492  Cust_1579   391.9000      0.10   
54    Ord_4682   Prod_4  SHP_6531  Cust_1579  1909.0065      0.01   
55    Ord_4657   Prod_5  SHP_6489  Cust_1579   418.0300      0.00   
56    Ord_4410   Prod_5  SHP_6146  Cust_1474   605.7700      0.05   
57    Ord_4546   Prod_1  SHP_6327  Cust_1474  5208.7800      0.05   
58    Ord_4499   Prod_6  SHP_6264  Cust_1474    67.4900      0.06   
59    Ord_4552   Prod_4  SHP_6335  Cust_1474   284.4525      0.06   
60    Ord_4552  Prod_12  SHP_6335  Cust_1474   104.7000      0.09   
61    Ord_4497  Prod_13  SHP_6261  Cust_1474   211.9700      0.06   
62    Ord_4410   Prod_6  SHP_6146  Cust_1474  1480.9100      0.00   
63    Ord_4499  Prod_13  SHP_6265  Cust_1474     6.7600      0.02   
64    Ord_4475   Prod_4  SHP_6234  Cust_1474  7640.2250      0.07   
65    Ord_4547   Prod_6  SHP_6328  Cust_1474    23.4400      0.05   
66    Ord_4360  Prod_11  SHP_6079  Cust_1474  1736.4100      0.10   
67    Ord_4541   Prod_2  SHP_6322  Cust_1474   336.6500      0.07   
...        ...      ...       ...        ...        ...       ...   
8351  Ord_3584  Prod_15  SHP_4961  Cust_1266  2502.6700      0.10   
8352  Ord_3638   Prod_6  SHP_5037  Cust_1266    36.4300      0.04   
8353  Ord_3610  Prod_13  SHP_4999  Cust_1266    88.5900      0.05   
8354  Ord_3592   Prod_4  SHP_4973  Cust_1266  2614.3705      0.07   
8355  Ord_3592  Prod_17  SHP_4973  Cust_1266   636.5000      0.01   
8356  Ord_3639   Prod_5  SHP_5040  Cust_1266    40.3400      0.03   
8357  Ord_3610  Prod_14  SHP_4998  Cust_1266  1759.6500      0.06   
8358  Ord_3582   Prod_6  SHP_4959  Cust_1266   539.6600      0.00   
8359  Ord_3543   Prod_3  SHP_4906  Cust_1266   514.2200      0.02   
8360  Ord_3639  Prod_10  SHP_5038  Cust_1266  2173.2600      0.00   
8370  Ord_2696  Prod_13  SHP_3690  Cust_1006    62.7800      0.04   
8371  Ord_2624   Prod_4  SHP_3591  Cust_1006  4924.1350      0.07   
8372  Ord_2772   Prod_9  SHP_3806  Cust_1006    56.9000      0.03   
8373  Ord_2600  Prod_16  SHP_3560  Cust_1006   106.6400      0.10   
8374  Ord_2658   Prod_5  SHP_3637  Cust_1006  1082.6600      0.08   
8375  Ord_2772   Prod_3  SHP_3806  Cust_1006  1413.8200      0.10   
8376  Ord_2624   Prod_8  SHP_3590  Cust_1006  1211.0000      0.00   
8377  Ord_2722  Prod_12  SHP_3729  Cust_1006    34.0100      0.00   
8378  Ord_2706   Prod_2  SHP_3705  Cust_1006  1361.9100      0.05   
8379  Ord_2722   Prod_5  SHP_3730  Cust_1006  1008.9500      0.04   
8380  Ord_2772   Prod_6  SHP_3807  Cust_1006   308.9200      0.04   
8381  Ord_2696   Prod_4  SHP_3691  Cust_1006  2836.0505      0.01   
8382  Ord_2658   Prod_3  SHP_3636  Cust_1006   120.9800      0.00   
8383  Ord_2722   Prod_1  SHP_3731  Cust_1006  3508.3300      0.04   
8384  Ord_4620   Prod_3  SHP_6435  Cust_1577    59.6200      0.04   
8385  Ord_1833   Prod_3  SHP_2527   Cust_637   611.1600      0.04   
8386  

In [190]:
df2 = pd.merge(df1,prod,how="inner",on="Prod_id")

In [192]:
df3 = pd.merge(df2,shipping,how="inner",on="Ship_id")

In [194]:
df4 = pd.merge(df3,orders,how="inner",on="Ord_id")

In [196]:
df4.head()

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
0  Ord_5446  Prod_16  SHP_7609  Cust_1818   136.81      0.01              23   
1  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00              26   
2  Ord_5446   Prod_6  SHP_7608  Cust_1818   164.02      0.03              23   
3  Ord_2978  Prod_16  SHP_4112  Cust_1088   305.05      0.04              27   
4  Ord_5484  Prod_16  SHP_7663  Cust_1820   322.82      0.05              35   

    Profit  Shipping_Cost  Product_Base_Margin       ...         Region  \
0   -30.51           3.60                 0.56       ...           WEST   
1  1148.90           2.50                 0.59       ...           WEST   
2   -47.64           6.15                 0.37       ...           WEST   
3    23.12           3.37                 0.57       ...        ONTARIO   
4   -17.58           3.98                 0.56       ...           WEST   

  Customer_Segment Product_Category           Product_Sub_Category Order_ID_x  \
0        CORPORATE  OFFICE SUPPLIES  SCISSORS, RULERS AND TRIMMERS      36262   
1        CORPORATE       TECHNOLOGY   TELEPHONES AND COMMUNICATION      36262   
2        CORPORATE  OFFICE SUPPLIES                          PAPER      36262   
3      HOME OFFICE  OFFICE SUPPLIES  SCISSORS, RULERS AND TRIMMERS      37863   
4         CONSUMER  OFFICE SUPPLIES  SCISSORS, RULERS AND TRIMMERS      53026   

     Ship_Mode   Ship_Date Order_ID_y  Order_Date  Order_Priority  
0  REGULAR AIR  28-07-2010      36262  27-07-2010   NOT SPECIFIED  
1  EXPRESS AIR  27-07-2010      36262  27-07-2010   NOT SPECIFIED  
2  EXPRESS AIR  28-07-2010      36262  27-07-2010   NOT SPECIFIED  
3  REGULAR AIR  26-02-2011      37863  24-02-2011            HIGH  
4  REGULAR AIR  03-03-2012      53026  26-02-2012             LOW  

[5 rows x 22 columns]

In [199]:
df4.shape

(8399, 22)

In [1]:
import numpy as np
import pandas as pd

In [2]:
customer = pd.read_csv("D:/PGDDS/Python/global_sales_data/cust_dimen.csv")
market = pd.read_csv("D:/PGDDS/Python/global_sales_data/market_fact.csv")
orders = pd.read_csv("D:/PGDDS/Python/global_sales_data/orders_dimen.csv")
products = pd.read_csv("D:/PGDDS/Python/global_sales_data/prod_dimen.csv")
shipping = pd.read_csv("D:/PGDDS/Python/global_sales_data/shipping_dimen.csv")

In [3]:
customer.head()

Customer_Name Province   Region Customer_Segment Cust_id
0  MUHAMMED MACINTYRE  NUNAVUT  NUNAVUT   SMALL BUSINESS  Cust_1
1        BARRY FRENCH  NUNAVUT  NUNAVUT         CONSUMER  Cust_2
2       CLAY ROZENDAL  NUNAVUT  NUNAVUT        CORPORATE  Cust_3
3      CARLOS SOLTERO  NUNAVUT  NUNAVUT         CONSUMER  Cust_4
4        CARL JACKSON  NUNAVUT  NUNAVUT        CORPORATE  Cust_5

In [5]:
market.head()

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
0  Ord_5446  Prod_16  SHP_7609  Cust_1818   136.81      0.01              23   
1  Ord_5406  Prod_13  SHP_7549  Cust_1818    42.27      0.01              13   
2  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00              26   
3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.89      0.09              43   
4  Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.15      0.08              35   

    Profit  Shipping_Cost  Product_Base_Margin  
0   -30.51           3.60                 0.56  
1     4.56           0.93                 0.54  
2  1148.90           2.50                 0.59  
3   729.34          14.30                 0.37  
4  1219.87          26.30                 0.38

In [4]:
df1 = pd.merge(customer,market,how="inner",on="Cust_id")

In [5]:
df2 = pd.merge(df1,orders,how="inner",on="Ord_id")

In [6]:
df3 = pd.merge(df2,products,how="inner",on="Prod_id")

In [7]:
df4 = pd.merge(df3,shipping,how="inner",on="Ship_id")

In [15]:
df4.shape

(8399, 22)

In [16]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8399 entries, 0 to 8398
Data columns (total 22 columns):
Customer_Name           8399 non-null object
Province                8399 non-null object
Region                  8399 non-null object
Customer_Segment        8399 non-null object
Cust_id                 8399 non-null object
Ord_id                  8399 non-null object
Prod_id                 8399 non-null object
Ship_id                 8399 non-null object
Sales                   8399 non-null float64
Discount                8399 non-null float64
Order_Quantity          8399 non-null int64
Profit                  8399 non-null float64
Shipping_Cost           8399 non-null float64
Product_Base_Margin     8336 non-null float64
Order_ID_x              8399 non-null int64
Order_Date              8399 non-null object
Order_Priority          8399 non-null object
Product_Category        8399 non-null object
Product_Sub_Category    8399 non-null object
Order_ID_y              8399 non-nu

In [19]:
df4.describe()

Sales     Discount  Order_Quantity        Profit  Shipping_Cost  \
count   8399.000000  8399.000000     8399.000000   8399.000000    8399.000000   
mean    1775.878179     0.049671       25.571735    181.184424      12.838557   
std     3585.050525     0.031823       14.481071   1196.653371      17.264052   
min        2.240000     0.000000        1.000000 -14140.700000       0.490000   
25%      143.195000     0.020000       13.000000    -83.315000       3.300000   
50%      449.420000     0.050000       26.000000     -1.500000       6.070000   
75%     1709.320000     0.080000       38.000000    162.750000      13.990000   
max    89061.050000     0.250000       50.000000  27220.690000     164.730000   

       Product_Base_Margin    Order_ID_x    Order_ID_y  
count          8336.000000   8399.000000   8399.000000  
mean              0.512513  29965.179783  29965.179783  
std               0.135589  17260.883447  17260.883447  
min               0.350000      3.000000      3.000000  
25%               0.380000  15011.500000  15011.500000  
50%               0.520000  29857.000000  29857.000000  
75%               0.590000  44596.000000  44596.000000  
max               0.850000  59973.000000  59973.000000

In [21]:
final_merge = df4

In [24]:
df4.sort_values('Region').head(10)

Customer_Name     Province    Region Customer_Segment   Cust_id  \
4199        CHUCK SACHS  NOVA SCOTIA  ATLANTIC         CONSUMER  Cust_696   
2535  ELIZABETH MOFFITT  NOVA SCOTIA  ATLANTIC         CONSUMER  Cust_691   
2537       CHRIS CORTES  NOVA SCOTIA  ATLANTIC         CONSUMER  Cust_697   
2539         NORA PAIGE  NOVA SCOTIA  ATLANTIC   SMALL BUSINESS  Cust_703   
2540    KATRINA WILLMAN  NOVA SCOTIA  ATLANTIC         CONSUMER  Cust_705   
2542      MARK HABERLIN  NOVA SCOTIA  ATLANTIC   SMALL BUSINESS  Cust_715   
2543      MARK HABERLIN  NOVA SCOTIA  ATLANTIC   SMALL BUSINESS  Cust_715   
2544      BRENDAN MURRY  NOVA SCOTIA  ATLANTIC        CORPORATE  Cust_719   
2545       ALEX GRAYSON  NOVA SCOTIA  ATLANTIC         CONSUMER  Cust_723   
2548     JONI WASSERMAN  NOVA SCOTIA  ATLANTIC         CONSUMER  Cust_736   

        Ord_id  Prod_id   Ship_id      Sales  Discount     ...      \
4199  Ord_2042   Prod_5  SHP_2792  2208.3100      0.04     ...       
2535  Ord_1899   Prod_4  SHP_2605  2172.5150      0.06     ...       
2537  Ord_1946   Prod_4  SHP_2793  1295.5020      0.01     ...       
2539  Ord_2005   Prod_4  SHP_2740   568.7435      0.05     ...       
2540  Ord_2026   Prod_4  SHP_2770   206.2865      0.05     ...       
2542  Ord_1932   Prod_4  SHP_2648   462.3660      0.10     ...       
2543  Ord_1932  Prod_13  SHP_2648   336.4800      0.09     ...       
2544  Ord_1940   Prod_4  SHP_2657   623.1265      0.09     ...       
2545  Ord_2062   Prod_4  SHP_2818   821.7885      0.06     ...       
2548  Ord_1970   Prod_8  SHP_2694   184.7400      0.00     ...       

      Shipping_Cost  Product_Base_Margin  Order_ID_x  Order_Date  \
4199           4.80                 0.68       39780  07-06-2009   
2535           8.99                 0.57       15971  14-08-2009   
2537           3.99                 0.59       39842  19-12-2010   
2539           3.30                 0.39       16229  29-03-2009   
2540           5.03                 0.60       29473  15-02-2012   
2542           3.30                 0.81       33958  02-02-2011   
2543           5.37                 0.56       33958  02-02-2011   
2544           0.99                 0.57       38341  18-05-2009   
2545           5.00                 0.80       54053  14-02-2012   
2548           4.38                 0.75       55616  08-05-2011   

      Order_Priority Product_Category          Product_Sub_Category  \
4199             LOW        FURNITURE            OFFICE FURNISHINGS   
2535            HIGH       TECHNOLOGY  TELEPHONES AND COMMUNICATION   
2537          MEDIUM       TECHNOLOGY  TELEPHONES AND COMMUNICATION   
2539            HIGH       TECHNOLOGY  TELEPHONES AND COMMUNICATION   
2540          MEDIUM       TECHNOLOGY  TELEPHONES AND COMMUNICATION   
2542        CRITICAL       TECHNOLOGY  TELEPHONES AND COMMUNICATION   
2543        CRITICAL  OFFICE SUPPLIES           PENS & ART SUPPLIES   
2544          MEDIUM       TECHNOLOGY  TELEPHONES AND COMMUNICATION   
2545            HIGH       TECHNOLOGY  TELEPHONES AND COMMUNICATION   
2548            HIGH       TECHNOLOGY          COMPUTER PERIPHERALS   

     Order_ID_y    Ship_Mode   Ship_Date  
4199      39780  REGULAR AIR  09-06-2009  
2535      15971  REGULAR AIR  15-08-2009  
2537      39842  EXPRESS AIR  20-12-2010  
2539      16229  REGULAR AIR  31-03-2009  
2540      29473  REGULAR AIR  17-02-2012  
2542      33958  REGULAR AIR  04-02-2011  
2543      33958  REGULAR AIR  04-02-2011  
2544      38341  REGULAR AIR  18-05-2009  
2545      54053  EXPRESS AIR  15-02-2012  
2548      55616  REGULAR AIR  09-05-2011  

[10 rows x 22 columns]

In [28]:
df4.groupby('Region')['Sales'].mean()

Region
ATLANTIC                 1865.044633
NORTHWEST TERRITORIES    2032.607435
NUNAVUT                  1473.120044
ONTARIO                  1677.553384
PRARIE                   1663.132826
QUEBEC                   1933.668476
WEST                     1806.905713
YUKON                    1800.493304
Name: Sales, dtype: float64

In [30]:
df4.groupby(['Region','Province'])['Sales'].mean()

Region                 Province             
ATLANTIC               NEW BRUNSWICK            2118.301930
                       NEWFOUNDLAND             1255.171555
                       NOVA SCOTIA              1762.347764
                       PRINCE EDWARD ISLAND     1940.204976
NORTHWEST TERRITORIES  NORTHWEST TERRITORIES    2032.607435
NUNAVUT                NUNAVUT                  1473.120044
ONTARIO                ONTARIO                  1677.553384
PRARIE                 MANITOBA                 1731.209057
                       SASKACHEWAN              1604.004183
QUEBEC                 QUEBEC                   1933.668476
WEST                   ALBERTA                  1970.857215
                       BRITISH COLUMBIA         1680.957180
YUKON                  YUKON                    1800.493304
Name: Sales, dtype: float64

In [31]:
df4.groupby(['Region','Province'])['Sales'].mean().sort_values()

Region                 Province             
ATLANTIC               NEWFOUNDLAND             1255.171555
NUNAVUT                NUNAVUT                  1473.120044
PRARIE                 SASKACHEWAN              1604.004183
ONTARIO                ONTARIO                  1677.553384
WEST                   BRITISH COLUMBIA         1680.957180
PRARIE                 MANITOBA                 1731.209057
ATLANTIC               NOVA SCOTIA              1762.347764
YUKON                  YUKON                    1800.493304
QUEBEC                 QUEBEC                   1933.668476
ATLANTIC               PRINCE EDWARD ISLAND     1940.204976
WEST                   ALBERTA                  1970.857215
NORTHWEST TERRITORIES  NORTHWEST TERRITORIES    2032.607435
ATLANTIC               NEW BRUNSWICK            2118.301930
Name: Sales, dtype: float64

In [32]:
pd.DataFrame(df4.groupby(['Region','Province'])['Sales'].mean().sort_values())

Sales
Region                Province                          
ATLANTIC              NEWFOUNDLAND           1255.171555
NUNAVUT               NUNAVUT                1473.120044
PRARIE                SASKACHEWAN            1604.004183
ONTARIO               ONTARIO                1677.553384
WEST                  BRITISH COLUMBIA       1680.957180
PRARIE                MANITOBA               1731.209057
ATLANTIC              NOVA SCOTIA            1762.347764
YUKON                 YUKON                  1800.493304
QUEBEC                QUEBEC                 1933.668476
ATLANTIC              PRINCE EDWARD ISLAND   1940.204976
WEST                  ALBERTA                1970.857215
NORTHWEST TERRITORIES NORTHWEST TERRITORIES  2032.607435
ATLANTIC              NEW BRUNSWICK          2118.301930

In [33]:
df4.columns

Index(['Customer_Name', 'Province', 'Region', 'Customer_Segment', 'Cust_id',
       'Ord_id', 'Prod_id', 'Ship_id', 'Sales', 'Discount', 'Order_Quantity',
       'Profit', 'Shipping_Cost', 'Product_Base_Margin', 'Order_ID_x',
       'Order_Date', 'Order_Priority', 'Product_Category',
       'Product_Sub_Category', 'Order_ID_y', 'Ship_Mode', 'Ship_Date'],
      dtype='object')

In [34]:
df4.groupby(['Product_Category'])['Profit'].mean()

Product_Category
FURNITURE           68.116607
OFFICE SUPPLIES    112.369074
TECHNOLOGY         429.207516
Name: Profit, dtype: float64

In [35]:
df4.groupby(['Product_Category','Product_Sub_Category'])['Profit'].mean()

Product_Category  Product_Sub_Category          
FURNITURE         BOOKCASES                         -177.683228
                  CHAIRS & CHAIRMATS                 387.693601
                  OFFICE FURNISHINGS                 127.446612
                  TABLES                            -274.411357
OFFICE SUPPLIES   APPLIANCES                         223.866498
                  BINDERS AND BINDER ACCESSORIES     335.970918
                  ENVELOPES                          195.864228
                  LABELS                              47.490174
                  PAPER                               36.949551
                  PENS & ART SUPPLIES                 11.950679
                  RUBBER BANDS                        -0.573575
                  SCISSORS, RULERS AND TRIMMERS      -54.161458
                  STORAGE & ORGANIZATION              12.205403
TECHNOLOGY        COMPUTER PERIPHERALS               124.389815
                  COPIERS AND FAX                   192

In [37]:
df4.groupby(['Product_Category','Product_Sub_Category'])['Profit'].describe()

count         mean  \
Product_Category Product_Sub_Category                                  
FURNITURE        BOOKCASES                        189.0  -177.683228   
                 CHAIRS & CHAIRMATS               386.0   387.693601   
                 OFFICE FURNISHINGS               788.0   127.446612   
                 TABLES                           361.0  -274.411357   
OFFICE SUPPLIES  APPLIANCES                       434.0   223.866498   
                 BINDERS AND BINDER ACCESSORIES   915.0   335.970918   
                 ENVELOPES                        246.0   195.864228   
                 LABELS                           288.0    47.490174   
                 PAPER                           1225.0    36.949551   
                 PENS & ART SUPPLIES              633.0    11.950679   
                 RUBBER BANDS                     179.0    -0.573575   
                 SCISSORS, RULERS AND TRIMMERS    144.0   -54.161458   
                 STORAGE & ORGANIZATION           546.0    12.205403   
TECHNOLOGY       COMPUTER PERIPHERALS             758.0   124.389815   
                 COPIERS AND FAX                   87.0  1923.695287   
                 OFFICE MACHINES                  337.0   913.094748   
                 TELEPHONES AND COMMUNICATION     883.0   358.948607   

                                                         std       min  \
Product_Category Product_Sub_Category                                    
FURNITURE        BOOKCASES                       1707.455501 -11053.60   
                 CHAIRS & CHAIRMATS              1482.276988  -3404.24   
                 OFFICE FURNISHINGS               463.997735  -1570.32   
                 TABLES                          1148.310769  -6474.65   
OFFICE SUPPLIES  APPLIANCES                       817.377547  -2172.14   
                 BINDERS AND BINDER ACCESSORIES  1349.974000   -961.50   
                 ENVELOPES                        479.703533   -201.60   
                 LABELS                           136.013924   -223.50   
                 PAPER                            217.200169   -331.63   
                 PENS & ART SUPPLIES               77.341605   -216.66   
                 RUBBER BANDS                      27.420725   -107.00   
                 SCISSORS, RULERS AND TRIMMERS    202.203379  -1759.58   
                 STORAGE & ORGANIZATION           848.234047  -2175.09   
TECHNOLOGY       COMPUTER PERIPHERALS             465.143093   -807.59   
                 COPIERS AND FAX                 4660.287752 -11861.46   
                 OFFICE MACHINES                 3627.391357 -14140.70   
                 TELEPHONES AND COMMUNICATION     642.970292   -888.16   

                                                      25%      50%        75%  \
Product_Category Product_Sub_Category                                           
FURNITURE        BOOKCASES                      -662.8000 -305.980   -78.3600   
                 CHAIRS & CHAIRMATS             -300.5225  -64.580   761.3175   
                 OFFICE FURNISHINGS              -34.0750   24.955   171.2975   
                 TABLES                         -694.3300 -352.960    31.2100   
OFFICE SUPPLIES  APPLIANCES                      -82.1000    6.375   448.6350   
                 BINDERS AND BINDER ACCESSORIES  -64.6400   -9.720    72.6650   
                 ENVELOPES                        -6.6925   39.315   204.1200   
                 LABELS                           10.5625   35.770    58.7400   
                 PAPER                           -69.2900  -14.350    55.8200   
                 PENS & ART SUPPLIES             -15.0300    0.820    24.6000   
                 RUBBER BANDS                    -11.2900   -1.720    11.7750   
                 SCISSORS, RULERS AND TRIMMERS   -64.6675  -31.015    -2.5575   
                 STORAGE & ORGANIZATION         -232.1675  -52.410    33.8725   
TECHNOLOGY       COMPUTER PERIPHERALS            -79.1475  

In [8]:
df4.columns

Index(['Customer_Name', 'Province', 'Region', 'Customer_Segment', 'Cust_id',
       'Ord_id', 'Prod_id', 'Ship_id', 'Sales', 'Discount', 'Order_Quantity',
       'Profit', 'Shipping_Cost', 'Product_Base_Margin', 'Order_ID_x',
       'Order_Date', 'Order_Priority', 'Product_Category',
       'Product_Sub_Category', 'Order_ID_y', 'Ship_Mode', 'Ship_Date'],
      dtype='object')

In [9]:
df4.groupby(['Ship_Mode'])['Profit'].mean()

Ship_Mode
DELIVERY TRUCK    235.292208
EXPRESS AIR       149.979969
REGULAR AIR       176.187049
Name: Profit, dtype: float64

In [10]:
df4.head()

Customer_Name Province   Region Customer_Segment  Cust_id  Ord_id  \
0  MUHAMMED MACINTYRE  NUNAVUT  NUNAVUT   SMALL BUSINESS   Cust_1   Ord_1   
1      CARLOS SOLTERO  NUNAVUT  NUNAVUT         CONSUMER   Cust_4  Ord_20   
2        CARL JACKSON  NUNAVUT  NUNAVUT        CORPORATE   Cust_5   Ord_5   
3      MONICA FEDERLE  NUNAVUT  NUNAVUT        CORPORATE   Cust_6   Ord_6   
4       NICOLE HANSEN  NUNAVUT  NUNAVUT   SMALL BUSINESS  Cust_24  Ord_55   

  Prod_id Ship_id    Sales  Discount     ...      Shipping_Cost  \
0  Prod_1   SHP_1   261.54      0.04     ...              35.00   
1  Prod_1  SHP_27   370.48      0.04     ...               4.51   
2  Prod_1   SHP_7   905.08      0.09     ...               6.22   
3  Prod_1   SHP_8  2781.82      0.07     ...              35.00   
4  Prod_1  SHP_72  3338.98      0.00     ...              35.00   

   Product_Base_Margin  Order_ID_x  Order_Date  Order_Priority  \
0                 0.80           3  13-10-2010             LOW   
1                 0.59        1792  08-11-2010             LOW   
2                  NaN         613  17-06-2011            HIGH   
3                  NaN         643  24-03-2011            HIGH   
4                 0.81        8833  04-05-2012             LOW   

  Product_Category    Product_Sub_Category Order_ID_y    Ship_Mode   Ship_Date  
0  OFFICE SUPPLIES  STORAGE & ORGANIZATION          3  REGULAR AIR  20-10-2010  
1  OFFICE SUPPLIES  STORAGE & ORGANIZATION       1792  REGULAR AIR  13-11-2010  
2  OFFICE SUPPLIES  STORAGE & ORGANIZATION        613  REGULAR AIR  18-06-2011  
3  OFFICE SUPPLIES  STORAGE & ORGANIZATION        643  EXPRESS AIR  25-03-2011  
4  OFFICE SUPPLIES  STORAGE & ORGANIZATION       8833  REGULAR AIR  08-05-2012  

[5 rows x 22 columns]

In [11]:
def is_postive(x):
    return x > 0


In [12]:
masterdf = df4

In [14]:
df4['is_profitable'] = df4['Profit'].apply(is_postive)
df4.head()

Customer_Name Province   Region Customer_Segment  Cust_id  Ord_id  \
0  MUHAMMED MACINTYRE  NUNAVUT  NUNAVUT   SMALL BUSINESS   Cust_1   Ord_1   
1      CARLOS SOLTERO  NUNAVUT  NUNAVUT         CONSUMER   Cust_4  Ord_20   
2        CARL JACKSON  NUNAVUT  NUNAVUT        CORPORATE   Cust_5   Ord_5   
3      MONICA FEDERLE  NUNAVUT  NUNAVUT        CORPORATE   Cust_6   Ord_6   
4       NICOLE HANSEN  NUNAVUT  NUNAVUT   SMALL BUSINESS  Cust_24  Ord_55   

  Prod_id Ship_id    Sales  Discount      ...        Product_Base_Margin  \
0  Prod_1   SHP_1   261.54      0.04      ...                       0.80   
1  Prod_1  SHP_27   370.48      0.04      ...                       0.59   
2  Prod_1   SHP_7   905.08      0.09      ...                        NaN   
3  Prod_1   SHP_8  2781.82      0.07      ...                        NaN   
4  Prod_1  SHP_72  3338.98      0.00      ...                       0.81   

   Order_ID_x  Order_Date  Order_Priority  Product_Category  \
0           3  13-10-2010             LOW   OFFICE SUPPLIES   
1        1792  08-11-2010             LOW   OFFICE SUPPLIES   
2         613  17-06-2011            HIGH   OFFICE SUPPLIES   
3         643  24-03-2011            HIGH   OFFICE SUPPLIES   
4        8833  04-05-2012             LOW   OFFICE SUPPLIES   

     Product_Sub_Category Order_ID_y    Ship_Mode   Ship_Date  is_profitable  
0  STORAGE & ORGANIZATION          3  REGULAR AIR  20-10-2010          False  
1  STORAGE & ORGANIZATION       1792  REGULAR AIR  13-11-2010          False  
2  STORAGE & ORGANIZATION        613  REGULAR AIR  18-06-2011           True  
3  STORAGE & ORGANIZATION        643  EXPRESS AIR  25-03-2011          False  
4  STORAGE & ORGANIZATION       8833  REGULAR AIR  08-05-2012          False  

[5 rows x 23 columns]

In [15]:
df4[['is_profitable']].head()

is_profitable
0          False
1          False
2           True
3          False
4          False

In [17]:
df4['is_profitable'] = df4['Profit'].apply(lambda x:x>0)

In [18]:
df4[['is_profitable']].head()

is_profitable
0          False
1          False
2           True
3          False
4          False

In [19]:
df4.columns

Index(['Customer_Name', 'Province', 'Region', 'Customer_Segment', 'Cust_id',
       'Ord_id', 'Prod_id', 'Ship_id', 'Sales', 'Discount', 'Order_Quantity',
       'Profit', 'Shipping_Cost', 'Product_Base_Margin', 'Order_ID_x',
       'Order_Date', 'Order_Priority', 'Product_Category',
       'Product_Sub_Category', 'Order_ID_y', 'Ship_Mode', 'Ship_Date',
       'is_profitable'],
      dtype='object')

In [21]:
df4.groupby(['Customer_Segment'])['is_profitable'].count()

Customer_Segment
CONSUMER          1649
CORPORATE         3076
HOME OFFICE       2032
SMALL BUSINESS    1642
Name: is_profitable, dtype: int64

In [22]:
df4.groupby(['Customer_Segment'])['is_profitable'].mean()

Customer_Segment
CONSUMER          0.500910
CORPORATE         0.481469
HOME OFFICE       0.498524
SMALL BUSINESS    0.496346
Name: is_profitable, dtype: float64

In [26]:
df4['Profit'].head()

0   -213.2
1     -5.4
2    127.7
3   -695.3
4   -846.7
Name: Profit, dtype: float64

In [25]:
df4['Profit'] = df4[['Profit']].apply(lambda x: round(x,1))

In [28]:
df4['profit_per_column'] = df4['Profit']/df4['Order_Quantity']

In [29]:
df4.columns

Index(['Customer_Name', 'Province', 'Region', 'Customer_Segment', 'Cust_id',
       'Ord_id', 'Prod_id', 'Ship_id', 'Sales', 'Discount', 'Order_Quantity',
       'Profit', 'Shipping_Cost', 'Product_Base_Margin', 'Order_ID_x',
       'Order_Date', 'Order_Priority', 'Product_Category',
       'Product_Sub_Category', 'Order_ID_y', 'Ship_Mode', 'Ship_Date',
       'is_profitable', 'profit_per_column'],
      dtype='object')

In [30]:
df4.head()

Customer_Name Province   Region Customer_Segment  Cust_id  Ord_id  \
0  MUHAMMED MACINTYRE  NUNAVUT  NUNAVUT   SMALL BUSINESS   Cust_1   Ord_1   
1      CARLOS SOLTERO  NUNAVUT  NUNAVUT         CONSUMER   Cust_4  Ord_20   
2        CARL JACKSON  NUNAVUT  NUNAVUT        CORPORATE   Cust_5   Ord_5   
3      MONICA FEDERLE  NUNAVUT  NUNAVUT        CORPORATE   Cust_6   Ord_6   
4       NICOLE HANSEN  NUNAVUT  NUNAVUT   SMALL BUSINESS  Cust_24  Ord_55   

  Prod_id Ship_id    Sales  Discount        ...          Order_ID_x  \
0  Prod_1   SHP_1   261.54      0.04        ...                   3   
1  Prod_1  SHP_27   370.48      0.04        ...                1792   
2  Prod_1   SHP_7   905.08      0.09        ...                 613   
3  Prod_1   SHP_8  2781.82      0.07        ...                 643   
4  Prod_1  SHP_72  3338.98      0.00        ...                8833   

   Order_Date  Order_Priority  Product_Category    Product_Sub_Category  \
0  13-10-2010             LOW   OFFICE SUPPLIES  STORAGE & ORGANIZATION   
1  08-11-2010             LOW   OFFICE SUPPLIES  STORAGE & ORGANIZATION   
2  17-06-2011            HIGH   OFFICE SUPPLIES  STORAGE & ORGANIZATION   
3  24-03-2011            HIGH   OFFICE SUPPLIES  STORAGE & ORGANIZATION   
4  04-05-2012             LOW   OFFICE SUPPLIES  STORAGE & ORGANIZATION   

  Order_ID_y    Ship_Mode   Ship_Date is_profitable  profit_per_column  
0          3  REGULAR AIR  20-10-2010         False         -35.533333  
1       1792  REGULAR AIR  13-11-2010         False          -0.192857  
2        613  REGULAR AIR  18-06-2011          True           5.804545  
3        643  EXPRESS AIR  25-03-2011         False         -33.109524  
4       8833  REGULAR AIR  08-05-2012         False         -21.167500  

[5 rows x 24 columns]

In [31]:
df4.pivot_table(values='Sales',index='Region',aggfunc='mean')

Sales
Region                            
ATLANTIC               1865.044633
NORTHWEST TERRITORIES  2032.607435
NUNAVUT                1473.120044
ONTARIO                1677.553384
PRARIE                 1663.132826
QUEBEC                 1933.668476
WEST                   1806.905713
YUKON                  1800.493304

In [32]:
df4.groupby('Region')['Profit'].mean()

Region
ATLANTIC                 221.260648
NORTHWEST TERRITORIES    255.464467
NUNAVUT                   35.965823
ONTARIO                  189.960241
PRARIE                   188.253810
QUEBEC                   179.802945
WEST                     149.175540
YUKON                    136.254797
Name: Profit, dtype: float64

In [35]:
df4.pivot_table(values='Sales',index='Product_Category',columns='Product_Sub_Category',aggfunc='mean')

Product_Sub_Category   APPLIANCES  BINDERS AND BINDER ACCESSORIES  \
Product_Category                                                    
FURNITURE                     NaN                             NaN   
OFFICE SUPPLIES       1698.137189                     1117.986437   
TECHNOLOGY                    NaN                             NaN   

Product_Sub_Category    BOOKCASES  CHAIRS & CHAIRMATS  COMPUTER PERIPHERALS  \
Product_Category                                                              
FURNITURE             4352.656296         4564.343394                   NaN   
OFFICE SUPPLIES               NaN                 NaN                   NaN   
TECHNOLOGY                    NaN                 NaN           1049.968259   

Product_Sub_Category  COPIERS AND FAX   ENVELOPES      LABELS  \
Product_Category                                                
FURNITURE                         NaN         NaN         NaN   
OFFICE SUPPLIES                   NaN  707.665854  135.352604   
TECHNOLOGY               12992.658621         NaN         NaN   

Product_Sub_Category  OFFICE FURNISHINGS  OFFICE MACHINES       PAPER  \
Product_Category                                                        
FURNITURE                      885.90585              NaN         NaN   
OFFICE SUPPLIES                      NaN              NaN  364.451314   
TECHNOLOGY                           NaN      6435.303086         NaN   

Product_Sub_Category  PENS & ART SUPPLIES  RUBBER BANDS  \
Product_Category                                          
FURNITURE                             NaN           NaN   
OFFICE SUPPLIES                263.992449     83.835922   
TECHNOLOGY                            NaN           NaN   

Product_Sub_Category  SCISSORS, RULERS AND TRIMMERS  STORAGE & ORGANIZATION  \
Product_Category                                                              
FURNITURE                                       NaN                     NaN   
OFFICE SUPPLIES                          562.474375             1960.041392   
TECHNOLOGY                                      NaN                     NaN   

Product_Sub_Category       TABLES  TELEPHONES AND COMMUNICATION  
Product_Category                                                 
FURNITURE             5252.100116                           NaN  
OFFICE SUPPLIES               NaN                           NaN  
TECHNOLOGY                    NaN                    2139.65323

In [37]:
help(pd.DataFrame.pivot_table)

Help on function pivot_table in module pandas.core.frame:

pivot_table(self, values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False, dropna=True, margins_name='All')
    Create a spreadsheet-style pivot table as a DataFrame. The levels in
    the pivot table will be stored in MultiIndex objects (hierarchical
    indexes) on the index and columns of the result DataFrame
    
    Parameters
    ----------
    values : column to aggregate, optional
    index : column, Grouper, array, or list of the previous
        If an array is passed, it must be the same length as the data. The
        list can contain any of the other types (except list).
        Keys to group by on the pivot table index.  If an array is passed,
        it is being used as the same manner as column values.
    columns : column, Grouper, array, or list of the previous
        If an array is passed, it must be the same length as the data. The
        list can contain any of the other types

In [38]:
df4.groupby(['Product_Category','Product_Sub_Category'])['Profit'].mean()

Product_Category  Product_Sub_Category          
FURNITURE         BOOKCASES                         -177.685185
                  CHAIRS & CHAIRMATS                 387.694041
                  OFFICE FURNISHINGS                 127.445558
                  TABLES                            -274.410249
OFFICE SUPPLIES   APPLIANCES                         223.868433
                  BINDERS AND BINDER ACCESSORIES     335.971148
                  ENVELOPES                          195.861382
                  LABELS                              47.488889
                  PAPER                               36.947755
                  PENS & ART SUPPLIES                 11.951027
                  RUBBER BANDS                        -0.572067
                  SCISSORS, RULERS AND TRIMMERS      -54.157639
                  STORAGE & ORGANIZATION              12.204396
TECHNOLOGY        COMPUTER PERIPHERALS               124.390237
                  COPIERS AND FAX                   192

In [41]:
df4.columns

Index(['Customer_Name', 'Province', 'Region', 'Customer_Segment', 'Cust_id',
       'Ord_id', 'Prod_id', 'Ship_id', 'Sales', 'Discount', 'Order_Quantity',
       'Profit', 'Shipping_Cost', 'Product_Base_Margin', 'Order_ID_x',
       'Order_Date', 'Order_Priority', 'Product_Category',
       'Product_Sub_Category', 'Order_ID_y', 'Ship_Mode', 'Ship_Date',
       'is_profitable', 'profit_per_column'],
      dtype='object')

In [55]:
df4.pivot_table(values=['Profit','Sales'],index=['Province','Region'],aggfunc='mean')

Profit        Sales
Province              Region                                        
ALBERTA               WEST                   175.661387  1970.857215
BRITISH COLUMBIA      WEST                   128.828952  1680.957180
MANITOBA              PRARIE                 172.039470  1731.209057
NEW BRUNSWICK         ATLANTIC               357.124768  2118.301930
NEWFOUNDLAND          ATLANTIC                83.965854  1255.171555
NORTHWEST TERRITORIES NORTHWEST TERRITORIES  255.464467  2032.607435
NOVA SCOTIA           ATLANTIC               183.971767  1762.347764
NUNAVUT               NUNAVUT                 35.965823  1473.120044
ONTARIO               ONTARIO                189.960241  1677.553384
PRINCE EDWARD ISLAND  ATLANTIC               148.635545  1940.204976
QUEBEC                QUEBEC                 179.802945  1933.668476
SASKACHEWAN           PRARIE                 202.337021  1604.004183
YUKON                 YUKON                  136.254797  1800.493304

In [47]:
import os
os.chdir("D:\PGDDS\Python\global_sales_data")

In [49]:
os.getcwd()

'D:\\PGDDS\\Python\\global_sales_data'

In [51]:
data = pd.read_csv("melbourne.csv")


In [52]:
data.head()

Suburb             Address  Rooms Type      Price Method SellerG  \
0  Abbotsford       68 Studley St      2    h        NaN     SS  Jellis   
1  Abbotsford        85 Turner St      2    h  1480000.0      S  Biggin   
2  Abbotsford     25 Bloomburg St      2    h  1035000.0      S  Biggin   
3  Abbotsford  18/659 Victoria St      3    u        NaN     VB  Rounds   
4  Abbotsford        5 Charles St      3    h  1465000.0     SP  Biggin   

         Date  Distance  Postcode      ...       Bathroom  Car  Landsize  \
0  03-09-2016       2.5    3067.0      ...            1.0  1.0     126.0   
1  03-12-2016       2.5    3067.0      ...            1.0  1.0     202.0   
2  04-02-2016       2.5    3067.0      ...            1.0  0.0     156.0   
3  04-02-2016       2.5    3067.0      ...            2.0  1.0       0.0   
4  04-03-2017       2.5    3067.0      ...            2.0  0.0     134.0   

   BuildingArea  YearBuilt  CouncilArea Lattitude  Longtitude  \
0           NaN        NaN        Yarra  -37.8014    144.9958   
1           NaN        NaN        Yarra  -37.7996    144.9984   
2          79.0     1900.0        Yarra  -37.8079    144.9934   
3           NaN        NaN        Yarra  -37.8114    145.0116   
4         150.0     1900.0        Yarra  -37.8093    144.9944   

              Regionname Propertycount  
0  Northern Metropolitan        4019.0  
1  Northern Metropolitan        4019.0  
2  Northern Metropolitan        4019.0  
3  Northern Metropolitan        4019.0  
4  Northern Metropolitan        4019.0  

[5 rows x 21 columns]

In [56]:
data

Suburb              Address  Rooms Type      Price Method  \
0          Abbotsford        68 Studley St      2    h        NaN     SS   
1          Abbotsford         85 Turner St      2    h  1480000.0      S   
2          Abbotsford      25 Bloomburg St      2    h  1035000.0      S   
3          Abbotsford   18/659 Victoria St      3    u        NaN     VB   
4          Abbotsford         5 Charles St      3    h  1465000.0     SP   
5          Abbotsford     40 Federation La      3    h   850000.0     PI   
6          Abbotsford          55a Park St      4    h  1600000.0     VB   
7          Abbotsford         16 Maugie St      4    h        NaN     SN   
8          Abbotsford         53 Turner St      2    h        NaN      S   
9          Abbotsford         99 Turner St      2    h        NaN      S   
10         Abbotsford       129 Charles St      2    h   941000.0      S   
11         Abbotsford         124 Yarra St      3    h  1876000.0      S   
12         Abbotsford  121/56 Nicholson St      2    u        NaN     PI   
13         Abbotsford        17 Raphael St      4    h        NaN      W   
14         Abbotsford        98 Charles St      2    h  1636000.0      S   
15         Abbotsford     217 Langridge St      3    h  1000000.0      S   
16         Abbotsford      18a Mollison St      2    t   745000.0      S   
17         Abbotsford   6/241 Nicholson St      1    u   300000.0      S   
18         Abbotsford        10 Valiant St      2    h  1097000.0      S   
19         Abbotsford  403/609 Victoria St      2    u   542000.0      S   
20         Abbotsford            2 Rich St      2    h        NaN     SP   
21         Abbotsford    25/84 Trenerry Cr      2    u   760000.0     SP   
22         Abbotsford    106/119 Turner St      1    u   481000.0     SP   
23         Abbotsford   411/8 Grosvenor St      2    u   700000.0     VB   
24         Abbotsford      40 Nicholson St      3    h  1350000.0     VB   
25         Abbotsford  123/56 Nicholson St      2    u   750000.0      S   
26         Abbotsford           22 Park St      4    h  1985000.0      S   
27         Abbotsford    13/84 Trenerry Cr      1    u   500000.0      S   
28         Abbotsford        45 William St      2    h  1172500.0      S   
29         Abbotsford   7/20 Abbotsford St      1    u   441000.0     SP   
...               ...                  ...    ...  ...        ...    ...   
23517   Vermont South        2 Settlers Ct      4    h  1295000.0     SP   
23518   Vermont South        9 Winswood Cl      4    h  1250000.0     PI   
23519        Viewbank        149 Graham Rd      5    h  1316000.0     SP   
23520        Viewbank       7 Northwood Dr      4    h        NaN     SP   
23521        Wantirna   16 chesterfield Ct      4    h   951000.0      S   
23522        Wantirna            9 eton Sq      4    h        NaN     PI   
23523  Wantirna South         12 Armagh Cr      4    h  1323000.0      S   
23524  Wantirna South        34 Fewster Dr      3    h   970000.0      S   
23525  Wantirna South           15 Mara Cl      4    h  1330000.0      S   
23526        Watsonia       2/14 Daours Ct      2    u   590000.0      S   
23527        Watsonia        76 Kenmare St      2    h   650000.0     PI   
23528  Watsonia North         22 Meakin St      3    h        NaN     PI   
23529        Werribee          6 Feijoa Ct      5    h        NaN      W   
23530        Werribee       11 Gundaroo Sq      4    h        NaN     PI   
23531        Werribee         91 Latham St      4    h   540000.0     PI   
23532        Werribee          5 Nuragi Ct      4    h   635000.0      S   
23533        Werribee             3 Sky Ct      3    h        NaN     PI   
23534  West Footscray      1/21 Waratah St      2    t   655000.0      S   
23535     Westmeadows           9 Black St      3    h   582000.0      S   
23536     Westmeadows      81 Hillcrest Dr      4    h   720000.0     VB   
23537   Wheelers Hill         12 Strada Cr      4    h  1245000

In [58]:
data.describe()

Rooms         Price      Distance      Postcode      Bedroom2  \
count  23547.000000  1.839600e+04  23546.000000  23546.000000  19066.000000   
mean       2.976048  1.056697e+06     10.306515   3109.782893      2.951956   
std        0.974501  6.419217e+05      6.016318     94.522190      0.996032   
min        1.000000  8.500000e+04      0.000000   3000.000000      0.000000   
25%        2.000000  6.330000e+05      6.200000   3047.000000      2.000000   
50%        3.000000  8.800000e+05      9.500000   3101.000000      3.000000   
75%        4.000000  1.302000e+06     13.000000   3150.000000      4.000000   
max       12.000000  9.000000e+06     48.100000   3978.000000     30.000000   

           Bathroom           Car       Landsize  BuildingArea     YearBuilt  \
count  19063.000000  18921.000000   17410.000000  10018.000000  11540.000000   
mean       1.570897      1.626235     551.783458    154.527895   1964.636742   
std        0.712684      0.974048    3544.288014    462.535765     37.595504   
min        0.000000      0.000000       0.000000      0.000000   1196.000000   
25%        1.000000      1.000000     181.000000     95.000000   1940.000000   
50%        1.000000      2.000000     448.000000    129.000000   1970.000000   
75%        2.000000      2.000000     656.000000    180.000000   2000.000000   
max       12.000000     26.000000  433014.000000  44515.000000   2106.000000   

          Lattitude    Longtitude  Propertycount  
count  19243.000000  19243.000000   23546.000000  
mean     -37.812434    145.000287    7517.480591  
std        0.079926      0.106071    4414.995634  
min      -38.184180    144.431620     129.000000  
25%      -37.859300    144.939300    4385.000000  
50%      -37.809700    145.004300    6567.000000  
75%      -37.759800    145.063100   10331.000000  
max      -37.407580    145.526350   21650.000000

In [63]:
data.shape
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23547 entries, 0 to 23546
Data columns (total 21 columns):
Suburb           23547 non-null object
Address          23547 non-null object
Rooms            23547 non-null int64
Type             23547 non-null object
Price            18396 non-null float64
Method           23547 non-null object
SellerG          23547 non-null object
Date             23547 non-null object
Distance         23546 non-null float64
Postcode         23546 non-null float64
Bedroom2         19066 non-null float64
Bathroom         19063 non-null float64
Car              18921 non-null float64
Landsize         17410 non-null float64
BuildingArea     10018 non-null float64
YearBuilt        11540 non-null float64
CouncilArea      15656 non-null object
Lattitude        19243 non-null float64
Longtitude       19243 non-null float64
Regionname       23546 non-null object
Propertycount    23546 non-null float64
dtypes: float64(12), int64(1), object(8)
memory usage: 3.8+ M

In [65]:
data.isnull()

Suburb  Address  Rooms   Type  Price  Method  SellerG   Date  Distance  \
0       False    False  False  False   True   False    False  False     False   
1       False    False  False  False  False   False    False  False     False   
2       False    False  False  False  False   False    False  False     False   
3       False    False  False  False   True   False    False  False     False   
4       False    False  False  False  False   False    False  False     False   
5       False    False  False  False  False   False    False  False     False   
6       False    False  False  False  False   False    False  False     False   
7       False    False  False  False   True   False    False  False     False   
8       False    False  False  False   True   False    False  False     False   
9       False    False  False  False   True   False    False  False     False   
10      False    False  False  False  False   False    False  False     False   
11      False    False  False  False  False   False    False  False     False   
12      False    False  False  False   True   False    False  False     False   
13      False    False  False  False   True   False    False  False     False   
14      False    False  False  False  False   False    False  False     False   
15      False    False  False  False  False   False    False  False     False   
16      False    False  False  False  False   False    False  False     False   
17      False    False  False  False  False   False    False  False     False   
18      False    False  False  False  False   False    False  False     False   
19      False    False  False  False  False   False    False  False     False   
20      False    False  False  False   True   False    False  False     False   
21      False    False  False  False  False   False    False  False     False   
22      False    False  False  False  False   False    False  False     False   
23      False    False  False  False  False   False    False  False     False   
24      False    False  False  False  False   False    False  False     False   
25      False    False  False  False  False   False    False  False     False   
26      False    False  False  False  False   False    False  False     False   
27      False    False  False  False  False   False    False  False     False   
28      False    False  False  False  False   False    False  False     False   
29      False    False  False  False  False   False    False  False     False   
...       ...      ...    ...    ...    ...     ...      ...    ...       ...   
23517   False    False  False  False  False   False    False  False     False   
23518   False    False  False  False  False   False    False  False     False   
23519   False    False  False  False  False   False    False  False     False   
23520   False    False  False  False   True   False    False  False     False   
23521   False    False  False  False  False   False    False  False     False   
23522   False    False  False  False   True   False    False  False     False   
23523   False    False  False  False  False   False    False  False     False   
23524   False    False  False  False  False   False    False  False     False   
23525   False    False  False  False  False   False    False  False     False   
23526   False    False  False  False  False   False    False  False     False   
23527   False    False  False  False  False   False    False  False     False   
23528   False    False  False  False   True   False    False  False     False   
23529   False    False  False  False   True   False    False  False     False   
23530   False    False  False  False   True   False    False  False     False   
23531   False    False  False  False  False   False    False  False     False   
23532   False    False  False  False  False   False    False  False     False   
23533   False    False  False  False   True   False    False  False     False   
23534   False    False  False  False  

In [67]:
data.isnull().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price             5151
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom2          4481
Bathroom          4484
Car               4626
Landsize          6137
BuildingArea     13529
YearBuilt        12007
CouncilArea       7891
Lattitude         4304
Longtitude        4304
Regionname           1
Propertycount        1
dtype: int64

In [70]:
data.isnull().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price             5151
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom2          4481
Bathroom          4484
Car               4626
Landsize          6137
BuildingArea     13529
YearBuilt        12007
CouncilArea       7891
Lattitude         4304
Longtitude        4304
Regionname           1
Propertycount        1
dtype: int64

In [71]:
data.isnull().any()

Suburb           False
Address          False
Rooms            False
Type             False
Price             True
Method           False
SellerG          False
Date             False
Distance          True
Postcode          True
Bedroom2          True
Bathroom          True
Car               True
Landsize          True
BuildingArea      True
YearBuilt         True
CouncilArea       True
Lattitude         True
Longtitude        True
Regionname        True
Propertycount     True
dtype: bool

In [74]:
data.isnull().any(axis=1)

0         True
1         True
2        False
3         True
4        False
5         True
6        False
7         True
8         True
9         True
10        True
11       False
12        True
13        True
14       False
15        True
16        True
17        True
18       False
19        True
20        True
21        True
22        True
23        True
24       False
25       False
26        True
27        True
28        True
29        True
         ...  
23517     True
23518     True
23519     True
23520     True
23521     True
23522     True
23523     True
23524     True
23525     True
23526     True
23527     True
23528     True
23529     True
23530     True
23531     True
23532     True
23533     True
23534     True
23535     True
23536     True
23537     True
23538     True
23539     True
23540     True
23541     True
23542     True
23543     True
23544     True
23545     True
23546     True
Length: 23547, dtype: bool

In [75]:
data.isnull().all()

Suburb           False
Address          False
Rooms            False
Type             False
Price            False
Method           False
SellerG          False
Date             False
Distance         False
Postcode         False
Bedroom2         False
Bathroom         False
Car              False
Landsize         False
BuildingArea     False
YearBuilt        False
CouncilArea      False
Lattitude        False
Longtitude       False
Regionname       False
Propertycount    False
dtype: bool

In [76]:
data.isnull().all(axis=1)

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...  
23517    False
23518    False
23519    False
23520    False
23521    False
23522    False
23523    False
23524    False
23525    False
23526    False
23527    False
23528    False
23529    False
23530    False
23531    False
23532    False
23533    False
23534    False
23535    False
23536    False
23537    False
23538    False
23539    False
23540    False
23541    False
23542    False
23543    False
23544    False
23545    False
23546    False
Length: 23547, dtype: bool

In [77]:
data.isnull().all(axis=1).sum()

0

In [78]:
data.isnull().sum(axis=1)

0        3
1        2
2        0
3        3
4        0
5        2
6        0
7        1
8        2
9        2
10       2
11       0
12       1
13       1
14       0
15       9
16       9
17       2
18       0
19       9
20       1
21       9
22       9
23       2
24       0
25       0
26       7
27       9
28       2
29       2
        ..
23517    2
23518    3
23519    3
23520    2
23521    1
23522    4
23523    3
23524    3
23525    1
23526    2
23527    1
23528    5
23529    4
23530    5
23531    9
23532    1
23533    5
23534    2
23535    3
23536    4
23537    2
23538    1
23539    2
23540    2
23541    1
23542    2
23543    8
23544    4
23545    1
23546    2
Length: 23547, dtype: int64

In [82]:
100*(data.isnull().sum()/len(data.index))

Suburb            0.000000
Address           0.000000
Rooms             0.000000
Type              0.000000
Price            21.875398
Method            0.000000
SellerG           0.000000
Date              0.000000
Distance          0.004247
Postcode          0.004247
Bedroom2         19.030025
Bathroom         19.042766
Car              19.645815
Landsize         26.062768
BuildingArea     57.455302
YearBuilt        50.991634
CouncilArea      33.511700
Lattitude        18.278337
Longtitude       18.278337
Regionname        0.004247
Propertycount     0.004247
dtype: float64

In [83]:
data.isnull().all()

Suburb           False
Address          False
Rooms            False
Type             False
Price            False
Method           False
SellerG          False
Date             False
Distance         False
Postcode         False
Bedroom2         False
Bathroom         False
Car              False
Landsize         False
BuildingArea     False
YearBuilt        False
CouncilArea      False
Lattitude        False
Longtitude       False
Regionname       False
Propertycount    False
dtype: bool

In [84]:
data1 = data

In [86]:
data = data.drop('BuildingArea',axis=1)
data = data.drop('YearBuilt',axis=1)
data = data.drop('CouncilArea',axis=1)

In [89]:
100*(data.isnull().sum()/len(data.index))

Suburb            0.000000
Address           0.000000
Rooms             0.000000
Type              0.000000
Price            21.875398
Method            0.000000
SellerG           0.000000
Date              0.000000
Distance          0.004247
Postcode          0.004247
Bedroom2         19.030025
Bathroom         19.042766
Car              19.645815
Landsize         26.062768
Lattitude        18.278337
Longtitude       18.278337
Regionname        0.004247
Propertycount     0.004247
dtype: float64

In [90]:
data[data.isnull().sum(axis=1) > 5]

Suburb              Address  Rooms Type      Price Method  \
15            Abbotsford     217 Langridge St      3    h  1000000.0      S   
16            Abbotsford      18a Mollison St      2    t   745000.0      S   
19            Abbotsford  403/609 Victoria St      2    u   542000.0      S   
21            Abbotsford    25/84 Trenerry Cr      2    u   760000.0     SP   
22            Abbotsford    106/119 Turner St      1    u   481000.0     SP   
27            Abbotsford    13/84 Trenerry Cr      1    u   500000.0      S   
33            Abbotsford     250 Langridge St      2    t   847000.0      S   
34            Abbotsford      16b Mollison St      2    h        NaN     PI   
45            Abbotsford    65/80 Trenerry Cr      1    u   480000.0      S   
46            Abbotsford  119/52 Nicholson St      1    u   423500.0      S   
52            Abbotsford    49/84 Trenerry Cr      2    h   700000.0      S   
60            Abbotsford    4/328 Johnston St      2    u        NaN     PI   
62            Abbotsford    82/84 Trenerry Cr      2    u   970000.0     SP   
65            Abbotsford    40/80 Trenerry Cr      3    h   927000.0      S   
74          Airport West          4/9 West Ct      2    t   420000.0     VB   
75          Airport West         1/36 York St      3    t   500000.0     VB   
76          Airport West          33 Bowes Av      5    h  1035000.0      S   
77          Airport West          89 Bowes Av      4    h   960000.0      S   
78          Airport West       45 Laurence Av      4    h   960000.0      S   
84          Airport West       81a Roberts Rd      3    h   680000.0     VB   
87          Airport West      3/24 Elstone Av      3    u   600000.0     VB   
89          Airport West         37a North St      3    t   760000.0     PI   
91          Airport West        1/69 Bowes Av      3    u   580000.0     VB   
92          Airport West       2/9 El Reno Cr      3    h   725000.0     PI   
93          Airport West       92 McNamara Av      4    h   758000.0      S   
95          Airport West       20 Creswell Av      3    h   970000.0      S   
97          Airport West          71 Bowes Av      4    h   985000.0      S   
99          Airport West       2/112 Parer Rd      2    u   509500.0     SP   
107         Airport West        7 McNamara Av      3    h   715000.0      S   
111         Airport West     1/41 Hillside Gr      2    t   460000.0     VB   
...                  ...                  ...    ...  ...        ...    ...   
23270            MacLeod          4 Tucker Wy      4    h   831000.0      S   
23271          Maidstone      88a Ballarat Rd      3    t   706000.0      S   
23290     Meadow Heights      22 Lightwood Cr      5    h   710000.0      S   
23291          Melbourne         505/1 Roy St      2    u        NaN     SP   
23292          Melbourne         505/1 Roy St      2    u        NaN      S   
23300            Mentone       20A Winsome St      3    t   905000.0      S   
23302          Mickleham         3 Selkirk Wy      2    h   335000.0      S   
23318       Moonee Ponds       55 Pattison St      2    h   700000.0     VB   
23333     Mount Waverley          19 Larch Cr      3    h        NaN     SN   
23337           Mulgrave         45 Carson St      3    t   826000.0      S   
23352          Northcote  2/241 Heidelberg Rd      2    t   770000.0     VB   
23363             Ormond        9a Bewdley St      4    t        NaN      S   
23384            Prahran         82 Murray St      2    h  1500000.0     VB   
23397          Reservoir        5a Kyneton Av      3    u   635000.0      S   
23398          Reservoir         13 Lawley St      4    h        NaN     PI   
23409           Richmond    10/9 Westbank Tce      2    u   410000.0     PI   
23412      Ringwood East     2/16 Bronhill Rd      4    t   850000.0     VB   
23418           Rowville       8 Lakeside Bvd      3    h   905000.0      S   
23424        Sandringham           4 Gipsy Wy      2    t        NaN

In [91]:
len(data[data.isnull().sum(axis=1) > 5])

4278

In [92]:
100*len(data[data.isnull().sum(axis=1) > 5])/len(data.index)

18.16791948018856

In [94]:
len(data.index)

23547

In [95]:
data = data[data.isnull().sum(axis=1)<=5]

In [96]:
len(data.index)

19269

In [97]:
100*(data.isnull().sum()/len(data.index))

Suburb            0.000000
Address           0.000000
Rooms             0.000000
Type              0.000000
Price            21.708444
Method            0.000000
SellerG           0.000000
Date              0.000000
Distance          0.000000
Postcode          0.000000
Bedroom2          1.053506
Bathroom          1.069075
Car               1.806010
Landsize          9.647621
Lattitude         0.134932
Longtitude        0.134932
Regionname        0.000000
Propertycount     0.000000
dtype: float64

In [98]:
data = data[~np.isnan(data['Price'])]
100*(data.isnull().sum()/len(data.index))

Suburb           0.000000
Address          0.000000
Rooms            0.000000
Type             0.000000
Price            0.000000
Method           0.000000
SellerG          0.000000
Date             0.000000
Distance         0.000000
Postcode         0.000000
Bedroom2         1.053957
Bathroom         1.067215
Car              1.763224
Landsize         9.830306
Lattitude        0.145831
Longtitude       0.145831
Regionname       0.000000
Propertycount    0.000000
dtype: float64

In [99]:
len(data.index)

15086

In [101]:
data['Landsize'].describe()

count     13603.000000
mean        558.116371
std        3987.326586
min           0.000000
25%         176.500000
50%         440.000000
75%         651.000000
max      433014.000000
Name: Landsize, dtype: float64

In [103]:
data = data[~np.isnan(data['Landsize'])]
100*(data.isnull().sum()/len(data.index))

Suburb           0.000000
Address          0.000000
Rooms            0.000000
Type             0.000000
Price            0.000000
Method           0.000000
SellerG          0.000000
Date             0.000000
Distance         0.000000
Postcode         0.000000
Bedroom2         0.000000
Bathroom         0.007351
Car              0.463133
Landsize         0.000000
Lattitude        0.161729
Longtitude       0.161729
Regionname       0.000000
Propertycount    0.000000
dtype: float64

In [104]:
data.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'Lattitude', 'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [105]:
data[np.isnan(data['Lattitude'])]

Suburb                Address  Rooms Type      Price  \
2572              Burwood           23 Monica St      3    h   990000.0   
3257         Clifton Hill  3/268 Alexandra Pde E      1    u   363000.0   
4485            Footscray          483 Barkly St      3    t   781000.0   
5170         Hampton East           7 Seafoam St      4    t  1185000.0   
10745  Williamstown North         4/9 Adeline St      1    u   355000.0   
13223           Melbourne   1913/228 Abeckett St      3    u  1175000.0   
14008            Brooklyn          9 Richards Ct      3    h   750000.0   
14132     North Melbourne   13/201 Abbotsford St      2    t   755000.0   
14139      Oakleigh South            4 Druitt St      4    h  1205500.0   
14142      Oakleigh South        298 Warrigal Rd      3    h   799999.0   
14143      Oakleigh South            11 Yarra Ct      5    h  1200000.0   
14976            Essendon        9 Washington St      3    h  1520000.0   
15278              Seddon          60 Station Rd      4    h  1500000.0   
15561             Croydon       3 Silvergrass Ct      3    h   630000.0   
16358          Kensington     201/102 Rankins Rd      2    u   876000.0   
16564          Strathmore          48 Lebanon St      3    h   950000.0   
17616          Kensington     109/102 Rankins Rd      1    u   410000.0   
17620         Keysborough          19 Denmark Rd      5    h  1100000.0   
18141               Lalor           83 Rotino Cr      3    t   463000.0   
18614           Mickleham        17 Primavera Dr      4    h   610000.0   
18793             Wollert      13 Strathalbyn Ch      4    h   631000.0   
18995           Greenvale         40 Frontier Av      3    t   470000.0   

      Method        SellerG        Date  Distance  Postcode  Bedroom2  \
2572      VB      Fletchers  17-09-2016      11.7    3125.0       3.0   
3257       S  hockingstuart  27-06-2016       3.4    3068.0       1.0   
4485       S            Jas  27-11-2016       6.4    3011.0       3.0   
5170       S             RT  28-05-2016      14.5    3188.0       4.0   
10745      S        Sweeney  27-11-2016       8.9    3016.0       1.0   
13223     PI           Icon  29-04-2017       2.8    3000.0       3.0   
14008      S  hockingstuart  20-05-2017      10.9    3012.0       3.0   
14132     PI         Nelson  29-04-2017       2.3    3051.0       2.0   
14139      S       Woodards  22-04-2017      14.7    3167.0       4.0   
14142      S       Woodards  29-04-2017      14.7    3167.0       3.0   
14143     PI         Buxton  29-04-2017      14.7    3167.0       5.0   
14976      S           Brad  03-06-2017       7.5    3040.0       3.0   
15278     SP        Sweeney  03-06-2017       5.1    3011.0       4.0   
15561      S        McGrath  17-06-2017      23.0    3136.0       3.0   
16358      S        Rendina  24-06-2017       3.4    3031.0       2.0   
16564     PI      Considine  24-06-2017       8.2    3041.0       3.0   
17616     PI        Rendina  08-07-2017       3.4    3031.0       1.0   
17620     PI       VicHomes  08-07-2017      25.2    3173.0       5.0   
18141      S            HAR  12-08-2017      16.3    3075.0       3.0   
18614      S            Ray  15-07-2017      20.6    3064.0       4.0   
18793     PI  hockingstuart  15-07-2017      25.5    3750.0       4.0   
18995     SP          Barry  22-07-2017      20.4    3059.0       3.0   

       Bathroom  Car  Landsize  Lattitude  Longtitude  \
2572        2.0  2.0     263.0        NaN         NaN   
3257        1.0  1.0       0.0        NaN         NaN   
4485        2.0  2.0      98.0        NaN         NaN   
5170        3.0  1.0     300.0        NaN         NaN   
10745       1.0  1.0      46.0        NaN         NaN   
13223       3.0  2.0       0.0        NaN         NaN   
14008       1.0  2.0     667.0        NaN         NaN   
14132       1.0  1.0    1537.0        NaN         NaN   
14139       2.0  2.0     553.0        NaN         NaN   
14142       2.0  4.0     590.0        NaN  

In [106]:
data.loc[:,['Lattitude','Longtitude']].describe()

Lattitude    Longtitude
count  13581.000000  13581.000000
mean     -37.809204    144.995221
std        0.079257      0.103913
min      -38.182550    144.431810
25%      -37.856820    144.929600
50%      -37.802360    145.000100
75%      -37.756400    145.058320
max      -37.408530    145.526350

In [108]:
data.loc[np.isnan(data['Lattitude']),['Lattitude']] = data['Lattitude'].mean()
data.loc[np.isnan(data['Longtitude']),['Longtitude']] = data['Longtitude'].mean()

C:\Users\narla\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


In [109]:
100*(data.isnull().sum()/len(data.index))

Suburb           0.000000
Address          0.000000
Rooms            0.000000
Type             0.000000
Price            0.000000
Method           0.000000
SellerG          0.000000
Date             0.000000
Distance         0.000000
Postcode         0.000000
Bedroom2         0.000000
Bathroom         0.007351
Car              0.463133
Landsize         0.000000
Lattitude        0.000000
Longtitude       0.000000
Regionname       0.000000
Propertycount    0.000000
dtype: float64

In [111]:
data['Car'] = data['Car'].astype('category')

In [112]:
data['Car'].value_counts()

2.0     5606
1.0     5515
0.0     1026
3.0      748
4.0      507
5.0       63
6.0       54
8.0        9
7.0        8
10.0       3
9.0        1
Name: Car, dtype: int64

In [114]:
data.loc[pd.isnull(data['Car']),['Car']] = 2 

In [115]:
100*(data.isnull().sum()/len(data.index))

Suburb           0.000000
Address          0.000000
Rooms            0.000000
Type             0.000000
Price            0.000000
Method           0.000000
SellerG          0.000000
Date             0.000000
Distance         0.000000
Postcode         0.000000
Bedroom2         0.000000
Bathroom         0.007351
Car              0.000000
Landsize         0.000000
Lattitude        0.000000
Longtitude       0.000000
Regionname       0.000000
Propertycount    0.000000
dtype: float64

In [116]:
data['Bathroom'] = data['Bathroom'].astype('category')
data['Bathroom'].value_counts()

1.0    7517
2.0    4987
3.0     921
4.0     106
0.0      34
5.0      28
6.0       5
8.0       2
7.0       2
Name: Bathroom, dtype: int64

In [118]:
data.loc[pd.isnull(data['Bathroom']),['Bathroom']] = 1

In [119]:
100*(data.isnull().sum()/len(data.index))

Suburb           0.0
Address          0.0
Rooms            0.0
Type             0.0
Price            0.0
Method           0.0
SellerG          0.0
Date             0.0
Distance         0.0
Postcode         0.0
Bedroom2         0.0
Bathroom         0.0
Car              0.0
Landsize         0.0
Lattitude        0.0
Longtitude       0.0
Regionname       0.0
Propertycount    0.0
dtype: float64